
name: GitHub Actions

on: [push]

jobs:

  python:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run formatter
        working-directory: functions
        run: poetry run black --diff --check .
